name: Build PHP 8.4.11 ARM64 Tarball

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export PHP ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --target export \
            -o type=tar,dest=php8-arm64.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php8-arm64-tarball
          path: php8-arm64.tar
