name: Build PHP 8.4.11 ARM64 tarball

on:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARM64 PHP tarball
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --target export \
            --output type=tar,dest=php8-arm64.tar \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php8-arm64-tar
          path: php8-arm64.tar
