name: DockerBuild ARM64

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version patch"
        required: true
        default: "8.4.11"
      yyyymmdd:
        description: "expiry date (YYYY-MM-DD)"
        required: false
        default: "2099-12-31"

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export PHP ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --target export \
            --build-arg VERSION=${{ github.event.inputs.version }} \
            --build-arg YYYYMMDD=${{ github.event.inputs.yyyymmdd }} \
            -o type=tar,dest=php-${{ github.event.inputs.version }}-arm64.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: php-${{ github.event.inputs.version }}-arm64-tarball
          path: php-${{ github.event.inputs.version }}-arm64.tar
