name: Build PHP 8.0.30 Custom

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'PHP source'
        required: true
        default: 'php.net'
        type: choice
        options:
          - php.net
          - absurd121

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout patch repo
        uses: actions/checkout@v4

      - name: Get PHP source
        run: |
          if [ "${{ github.event.inputs.source }}" = "php.net" ]; then
            wget https://www.php.net/distributions/php-8.0.30.tar.gz
            tar -xzf php-8.0.30.tar.gz
            mv php-8.0.30 php-src
          else
            git clone --branch php-8.3.12 https://github.com/absurd121/php-8.0.30.git php-src
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libxml2-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev \
            libxpm-dev \
            libzip-dev \
            libonig-dev \
            libreadline-dev \
            pkg-config \
            bison \
            re2c \
            autoconf

      - name: Replace modified files
        run: |
          cp config.m4 php-src/ext/zlib/config.m4
          cp zend_language_scanner.l php-src/Zend/zend_language_scanner.l

      - name: Configure & Build PHP
        run: |
          cd php-src
          ./buildconf --force
          ./configure --prefix=$HOME/php8-custom \
            --with-zlib \
            --enable-mbstring \
            --with-curl \
            --with-openssl \
            --enable-zip \
            --with-readline
          make -j$(nproc)
          make install

      - name: Pack build
        run: |
          cd $HOME
          tar -czf php8-custom.tar.gz php8-custom

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php8-custom
          path: $HOME/php8-custom.tar.gz
