name: Build PHP 7.4.33 Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo (patch files)
        uses: actions/checkout@v3

      - name: Checkout clean PHP source
        uses: actions/checkout@v3
        with:
          repository: absurd121/php-7.4.33
          path: php-src
          token: ${{ secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libxml2-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev \
            libxpm-dev \
            libzip-dev \
            libonig-dev \
            libreadline-dev \
            pkg-config \
            bison \
            re2c \
            autoconf

      - name: Replace modified files
        run: |
          cp config.m4 php-src/ext/zlib/config.m4
          cp zend_language_scanner.l php-src/Zend/zend_language_scanner.l

      - name: Configure & Build
        run: |
          cd php-src
          ./buildconf --force
          ./configure --prefix=$HOME/php7-custom \
            --with-zlib \
            --enable-mbstring \
            --with-curl \
            --with-openssl \
            --enable-zip \
            --with-readline
          make -j$(nproc)
          make install

      - name: Pack build
        run: |
          cd $HOME
          tar -czf php7-custom.tar.gz php7-custom

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: php7-custom
          path: $HOME/php7-custom.tar.gz
